language: node_js
node_js:
    - 4
addons:
    - firefox: "latest"
    - sauce_connect: true
before_install:
    - npm install -g npm@3
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
